{% set name = "nbclassic" %}
{% set version = "0.3.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c332322864a0bf5866dec3149b4863d092178f144749183a704d39f0ebb7947d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - jupyter-nbclassic = nbclassic.notebookapp:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - jupyter_server >=1.8.0,<2.0.0
    - notebook <7

test:
  imports:
    - nbclassic
  commands:
    - pip check
    - jupyter nbclassic --help
  requires:
    - pip

about:
  home: http://github.com/jupyterlab/nbclassic
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Jupyter Notebook as a Jupyter Server Extension.

  description: |
    This project prepares for a future where JupyterLab and other frontends
    switch to Jupyter Server for their Python Web application backend. Using
    this package, users can launch Jupyter Notebook, JupyterLab and other
    frontends side-by-side on top of the new Python server backend.
  dev_url: https://github.com/jupyterlab/nbclassic

extra:
  recipe-maintainers:
    - jasongrout
    - afshin
    - jtpio
    - bollwyvl
