{% set version = "0.4.2" %}

package:
  name: nbclassic
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nbclassic/nbclassic-{{ version }}.tar.gz
  sha256: b00694d33e844e0f6d02bb6aa4b32e7342d03e27d21b73003ac200978e1bd61a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - jupyter-nbclassic = nbclassic.notebookapp:main

requirements:
  host:
    - jupyter-packaging >=0.9,<1
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - jupyter_server >=1.8.0
    - notebook <7
    - notebook-shim >=0.1.0

test:
  imports:
    - nbclassic
    - m2-grep  # [win]
  commands:
    - pip check
    - jupyter nbclassic --help
    - jupyter server extension list
    - jupyter server extension list 1>server_extensions 2>&1
    - cat server_extensions | grep -iE "nbclassic.*enabled"
    - cat server_extensions | grep -iE "nbclassic.*OK"
  requires:
    - pip

about:
  home: http://github.com/jupyterlab/nbclassic
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Jupyter Notebook as a Jupyter Server Extension.

  description: |
    This project prepares for a future where JupyterLab and other frontends
    switch to Jupyter Server for their Python Web application backend. Using
    this package, users can launch Jupyter Notebook, JupyterLab and other
    frontends side-by-side on top of the new Python server backend.
  dev_url: https://github.com/jupyterlab/nbclassic

extra:
  recipe-maintainers:
    - jasongrout
    - afshin
    - jtpio
    - bollwyvl
