{% set version = "0.4.0" %}

package:
  name: nbclassic
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nbclassic/nbclassic-{{ version }}.tar.gz
  sha256: dfdab838f41d60f4d66b4af143cea250d32a0fa8573116921ea6532d1710aa27

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - jupyter-bundlerextension = nbclassic.bundler.bundlerextensions:main
    - jupyter-nbclassic = nbclassic.notebookapp:main
    - jupyter-nbextension = nbclassic.nbextensions:main
    - jupyter-serverextension = nbclassic.serverextensions:main

requirements:
  host:
    - jupyter-packaging >=0.9,<1
    - python >=3.7
    - pip
  run:
    - argon2-cffi
    - ipykernel
    - ipython_genutils
    - jinja2
    - jupyter_client >=6.1.1
    - jupyter_core >=4.6.1
    - jupyter_server >=1.8
    - nbconvert >=5
    - nbformat
    - nest-asyncio >=1.5
    - notebook_shim >=0.1.0
    - prometheus_client
    - python >=3.7
    - pyzmq >=17
    - send2trash >=1.8.0
    - terminado >=0.8.3
    - tornado >=6.1
    - traitlets >=4.2.1

test:
  imports:
    - nbclassic
  requires:
    - pip
  commands:
    - pip check
    - jupyter nbclassic --help
    - jupyter nbextension --help
    - jupyter serverextension --help
    - jupyter bundlerextension --help

about:
  home: http://github.com/jupyterlab/nbclassic
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A web-based notebook environment for interactive computing
  dev_url: https://github.com/jupyter/nbclassic
  doc_url: https://jupyter-notebook.readthedocs.io
  description: |
    The Jupyter NbClassic is a web application that allows you to create and
    share documents that contain live code, equations, visualizations, and
    explanatory text. The NbClassic has support for multiple programming
    languages, sharing, and interactive widgets.

extra:
  recipe-maintainers:
    - jasongrout
    - afshin
    - jtpio
    - bollwyvl
