# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.2.0"

package:
  name: nbclassic
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/n/nbclassic/nbclassic-${{ version }}.tar.gz
  sha256: 1ae3b30a4d051332559b6d0eaba34c20ada51a73c95a7f35954c126e6a5c80fd

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-verison-check
  python:
    entry_points:
      - jupyter-nbclassic = nbclassic.notebookapp:main
      - jupyter-nbclassic-bundlerextension = nbclassic.bundler.bundlerextensions:main
      - jupyter-nbclassic-extension = nbclassic.nbextensions:main
      - jupyter-nbclassic-serverextension = nbclassic.serverextensions:main

requirements:
  host:
    - babel
    - jupyter_server >=1.17.0
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - ipykernel
    - ipython_genutils
    - nest-asyncio >=1.5
    - notebook-shim >=0.2.3
    - python >=${{ python_min }}

tests:
  - python:
      imports: nbclassic
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - if: win
          then:
            - m2-grep
    script:
      - jupyter nbclassic --help
      - jupyter nbclassic-extension --help
      - jupyter nbclassic-serverextension --help
      - jupyter nbclassic-bundlerextension --help
      - jupyter server extension list
      - jupyter server extension list 1>server_extensions 2>&1
      - cat server_extensions | grep -iE "nbclassic.*enabled"
      - cat server_extensions | grep -iE "nbclassic.*OK\"

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A web-based notebook environment for interactive computing
  homepage: http://github.com/jupyterlab/nbclassic
  documentation: https://jupyter-notebook.readthedocs.io
  description: |
    The Jupyter NbClassic is a web application that allows you to create and
    share documents that contain live code, equations, visualizations, and
    explanatory text. The NbClassic has support for multiple programming
    languages, sharing, and interactive widgets.

extra:
  recipe-maintainers:
    - jasongrout
    - afshin
    - jtpio
    - bollwyvl
