# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.3.3"

package:
  name: nbclassic
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/n/nbclassic/nbclassic-${{ version }}.tar.gz
  sha256: 434228763f8cee754318cd6dfa42370db191af630dabab8e30bafc8c1aa3eee6

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - jupyter-nbclassic = nbclassic.notebookapp:main
      - jupyter-nbclassic-bundlerextension = nbclassic.bundler.bundlerextensions:main
      - jupyter-nbclassic-extension = nbclassic.nbextensions:main
      - jupyter-nbclassic-serverextension = nbclassic.serverextensions:main

requirements:
  host:
    - babel
    - hatch-jupyter-builder >=0.9.1
    - hatchling
    - jupyter_server >=1.17.0
    - pip
    - python ${{ python_min }}.*
  run:
    - ipykernel
    - ipython_genutils
    - nest-asyncio >=1.5
    - notebook-shim >=0.2.3
    - python >=${{ python_min }}

tests:
  - python:
      imports: nbclassic
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - jupyter nbclassic --help
      - jupyter nbclassic-extension --help
      - jupyter nbclassic-serverextension --help
      - jupyter nbclassic-bundlerextension --help
      - jupyter server extension list
      - jupyter server extension list | python -c "import re, sys; assert re.search(r'nbclassic.*enabled', sys.stdin.read())"
      - jupyter server extension list | python -c "import re, sys; assert re.search(r'nbclassic.*${{ version | replace('.', '\\.') }}.*OK', sys.stdin.read())"
  - files:
      recipe:
        - run_test.py
      source:
        - tests/
    requirements:
      run:
        - nbval
        - pytest-cov
        - pytest-jupyter
        - pytest-tornasync
        - requests
        - testpath
        - python ${{ python_min }}.*
        - if: unix
          then:
            - requests-unixsocket
    script:
      - python run_test.py

about:
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - nbclassic/static/components/backbone/LICENSE
    - nbclassic/static/components/bootstrap/LICENSE
    - nbclassic/static/components/bootstrap-tour/LICENSE
    - nbclassic/static/components/codemirror/LICENSE
    - nbclassic/static/components/font-awesome/README.md
    - nbclassic/static/components/google-caja-sanitizer/README.md
    - nbclassic/static/components/jed/README.md
    - nbclassic/static/components/jquery-typeahead/LICENSE
    - nbclassic/static/components/jquery-ui/LICENSE.txt
    - nbclassic/static/components/marked/LICENSE.md
    - nbclassic/static/components/MathJax/LICENSE
    - nbclassic/static/components/MathJax/fonts/HTML-CSS/STIX-Web/OFL.txt
    - nbclassic/static/components/moment/LICENSE
    - nbclassic/static/components/react/LICENSE
    - nbclassic/static/components/requirejs-text/LICENSE
    - nbclassic/static/components/underscore/LICENSE
  summary: Jupyter Notebook as a Jupyter Server extension.
  homepage: https://github.com/jupyter/nbclassic
  documentation: https://nbclassic.readthedocs.io

extra:
  recipe-maintainers:
    - jasongrout
    - afshin
    - jtpio
    - bollwyvl
