# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.3.0"

package:
  name: nbclassic
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/n/nbclassic/nbclassic-${{ version }}.tar.gz
  sha256: 1ae3b30a4d051332559b6d0eaba34c20ada51a73c95a7f35954c126e6a5c80fd

build:
  number: 0
  noarch: python
  script:
    - yarn
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - jupyter-nbclassic = nbclassic.notebookapp:main
      - jupyter-nbclassic-bundlerextension = nbclassic.bundler.bundlerextensions:main
      - jupyter-nbclassic-extension = nbclassic.nbextensions:main
      - jupyter-nbclassic-serverextension = nbclassic.serverextensions:main

requirements:
  host:
    - babel
    - hatch-jupyter-builder >=0.9.1
    - hatchling
    - jupyter_server >=1.17.0
    - pip
    - python ${{ python_min }}.*
    - yarn <2
  run:
    - ipykernel
    - ipython_genutils
    - nest-asyncio >=1.5
    - notebook-shim >=0.2.3
    - python >=${{ python_min }}

tests:
  - python:
      imports: nbclassic
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - if: win
          then:
            - m2-grep
    script:
      - jupyter nbclassic --help
      - jupyter nbclassic-extension --help
      - jupyter nbclassic-serverextension --help
      - jupyter nbclassic-bundlerextension --help
      - jupyter server extension list
      - jupyter server extension list 1>server_extensions 2>&1
      - cat server_extensions | grep -iE "nbclassic.*enabled"
      - cat server_extensions | grep -iE "nbclassic.*${{ version | replace('.', '\\.') }}.*OK"
  - files:
      recipe:
        - run_test.py
      source:
        - tests/
    requirements:
      run:
      - nbval
      - pytest-cov
      - pytest-jupyter
      - pytest-tornasync
      - requests
      - testpath
      - python ${{ python_min }}.*
      - if: unix
        then:
          - requests-unixsocket
    script:
      - python run_test.py

about:
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - node_modules/@bower_components/backbone/LICENSE
    - node_modules/@bower_components/bootstrap/LICENSE
    - node_modules/@bower_components/bootstrap-tour/LICENSE
    - node_modules/@bower_components/codemirror/LICENSE
    - node_modules/@bower_components/font-awesome/README.md
    - node_modules/@bower_components/google-caja/README.md
    - node_modules/@bower_components/jed/README.md
    - node_modules/@bower_components/jquery-typeahead/LICENSE
    - node_modules/@bower_components/jquery-ui/LICENSE
    - node_modules/@bower_components/marked/LICENSE.md
    - node_modules/@bower_components/MathJax/LICENSE
    - node_modules/@bower_components/MathJax/fonts/HTML-CSS/STIX-Web/OFL.txt
    - node_modules/@bower_components/moment/LICENSE
    - node_modules/@bower_components/react/LICENSE
    - node_modules/@bower_components/requirejs/LICENSE
    - node_modules/@bower_components/requirejs-plugins/LICENSE.mdown
    - node_modules/@bower_components/requirejs-text/LICENSE
    - node_modules/@bower_components/text-encoding/LICENSE.md
    - node_modules/@bower_components/underscore/LICENSE
  summary: Jupyter Notebook as a Jupyter Server extension.
  homepage: https://github.com/jupyter/nbclassic
  documentation: https://nbclassic.readthedocs.io

extra:
  recipe-maintainers:
    - jasongrout
    - afshin
    - jtpio
    - bollwyvl
