conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
bot:
  inspection: hint-all

# `mamba` seems to fail with `test/downstreams`
build_with_mambabuild: false
